// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: follower.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :one

INSERT into
    user_followers (follower_id, following_id)
VALUES ($1, $2) ON CONFLICT (following_id, follower_id)
DO NOTHING
RETURNING follower_id, following_id
`

type FollowUserParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (UserFollower, error) {
	row := q.db.QueryRowContext(ctx, followUser, arg.FollowerID, arg.FollowingID)
	var i UserFollower
	err := row.Scan(&i.FollowerID, &i.FollowingID)
	return i, err
}

const unfollowUser = `-- name: UnfollowUser :one

DELETE FROM user_followers
WHERE
    follower_id = $1
    AND following_id = $2
RETURNING follower_id, following_id
`

type UnfollowUserParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) (UserFollower, error) {
	row := q.db.QueryRowContext(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	var i UserFollower
	err := row.Scan(&i.FollowerID, &i.FollowingID)
	return i, err
}
