// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: follower.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :one

INSERT into
    user_followers (user_id, follower_id)
VALUES ($1, $2) ON CONFLICT (user_id, follower_id)
DO NOTHING
RETURNING user_id, follower_id
`

type FollowUserParams struct {
	UserID     uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (UserFollower, error) {
	row := q.db.QueryRowContext(ctx, followUser, arg.UserID, arg.FollowerID)
	var i UserFollower
	err := row.Scan(&i.UserID, &i.FollowerID)
	return i, err
}
