basePath: /v1/api
definitions:
  github_com_SohamRatnaparkhi_blogx-backend-go_authentication_db_database.User:
    properties:
      bio:
        $ref: '#/definitions/sql.NullString'
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      isadmin:
        type: boolean
      lastName:
        type: string
      password:
        type: string
      updatedAt:
        type: string
    type: object
  github_com_SohamRatnaparkhi_blogx-backend-go_authentication_pkg_utils.DBUserResponse:
    properties:
      bio:
        $ref: '#/definitions/sql.NullString'
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  github_com_SohamRatnaparkhi_blogx-backend-go_authentication_pkg_utils.DbUserFullSchema:
    properties:
      bio:
        $ref: '#/definitions/sql.NullString'
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_admin:
        type: boolean
      last_name:
        type: string
      updated_at:
        type: string
    type: object
  github_com_SohamRatnaparkhi_blogx-backend-go_blog_db_database.CreatePostParams:
    properties:
      body:
        type: string
      id:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      userID:
        type: string
    type: object
  github_com_SohamRatnaparkhi_blogx-backend-go_blog_db_database.UpdatePostParams:
    properties:
      body:
        type: string
      id:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  github_com_SohamRatnaparkhi_blogx-backend-go_blog_pkg_utils.PostMap:
    properties:
      author_id:
        type: string
      body:
        type: string
      id:
        type: string
      likes:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      views:
        type: integer
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: This is the authentication server for blogx
  title: Authentication server
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user with email and password given in the body
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_authentication_pkg_utils.DBUserResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - authentication
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout a user
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_authentication_pkg_utils.DBUserResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a user with fist name, last name, email, password and
        bio given in the body
      parameters:
      - description: User details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_authentication_db_database.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_authentication_pkg_utils.DbUserFullSchema'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - authentication
  /blogs/addBlog:
    post:
      consumes:
      - application/json
      description: Create a post with title, body and tags given in the body
      parameters:
      - description: Post details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_blog_db_database.CreatePostParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_blog_pkg_utils.PostMap'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - posts
  /blogs/deleteBlog:
    delete:
      consumes:
      - application/json
      description: Delete a post with post id given in the body
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - posts
  /blogs/dislike:
    get:
      consumes:
      - application/json
      description: dislike a post with post id given as query parameter(post_id)
      parameters:
      - description: Post ID
        in: query
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - posts
  /blogs/like:
    get:
      consumes:
      - application/json
      description: Like a post with post id given as query parameter(post_id)
      parameters:
      - description: Post ID
        in: query
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - posts
  /blogs/updateBlog:
    patch:
      consumes:
      - application/json
      description: Update a post with title, body and tags given in the body
      parameters:
      - description: Post details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_blog_db_database.UpdatePostParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SohamRatnaparkhi_blogx-backend-go_blog_pkg_utils.PostMap'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - posts
swagger: "2.0"
