apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-blog
  namespace: blogx-cc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-blog
  template:
    metadata:
      labels:
        app: api-blog
    spec:
      containers:
      - name: api-blog
        image: sohamkr/blogx_blog:0.0
        env:
        - name: POSTGRES_DB
          value: blogx_db
        - name: POSTGRES_PASSWORD
          value: foobarbaz
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: foobarbaz
        - name: DB_NAME
          value: blogx_db
        - name: PORT
          value: "8081"
        - name: JWT_SECRET_KEY
          value: blogx_secret_key
        - name: BCRYPT_SALT_VALUE
          value: "12"
        - name: DB_URL
          value: "postgres://postgres.roharsahwtuwaclsianl:mT5iappOoDza077K@aws-0-us-west-1.pooler.supabase.com:5432/postgres"
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-blog
  namespace: blogx-cc
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: api-blog

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-blog-hpa
  namespace: blogx-cc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-blog
  minReplicas: 2
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
