apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: blogx-cc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: sohamkr/blogx_haproxy:0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: blogx-cc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: haproxy
  type: LoadBalancer
